###############################################################################################################
##                                              Bot config                                                   ##
###############################################################################################################
token: ""   # Bot Token                                                                                      ##
clientId: ""   # Bot Client ID                                                                               ##
status: ""  # Status of the bot                                                                              ##
statusType: "" # Type of the status of the bot Watching, Playing, Listening, Streaming, Watching             ##
###############################################################################################################
##                                          Welcom embed config                                              ##
###############################################################################################################
channel: "" # Welcome Channel ID                                                                             ##
title: "" # Title of the welcome embed                                                                       ##
description: "" # Description of the welcome embed                                                           ##
color: "" # Color of the welcome embed                                                                       ##
footer: "" # Footer of the welcome embed                                                                     ##
footerIcon: "" # Footer icon of the welcome embed.                                                           ##
timestamp: true  # Timestamp of the welcome embed true = yes, false = no                                     ##
###############################################################################################################